import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/src/auth";
import "@/src/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Weskan",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </SessionProvider>
  );
}
